"""Contract every rollout agent runner implements, plus the loader the trainer uses.

``nano_swe/trainer/rollout/router.py``'s ``AgentRunnerActor`` drives rollouts by calling
``load_agent_runner(agent_path).execute(...)`` once per sample; this module defines what that
call receives and must return so any runner (this repo currently ships one, in
``swe_openhands.py``) plugs into ``SamplesGenerator``/``RemoteExperienceMaker`` unchanged.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from importlib import import_module
from typing import Any, List, Optional, Tuple, Union

import torch


def _first_scalar(value: Any) -> Optional[float]:
    """Normalize a tensor/list/scalar reward-ish value down to one Python float."""
    if value is None:
        return None
    if isinstance(value, torch.Tensor):
        return value.flatten()[0].item()
    if isinstance(value, (list, tuple)):
        return _first_scalar(value[0]) if value else None
    return float(value)


@dataclass
class Trajectory:
    """One rollout's full token stream, in the shape
    ``SamplesGenerator._process_response_into_experience`` expects.

    ``observation_tokens`` is the complete token sequence the policy actually saw and produced
    (prompt + every turn's generated and tool/environment tokens, in order). ``action_ranges``
    marks which ``[start, end)`` spans of it were generated BY the policy (only those get policy
    gradient); everything outside them — the prompt and tool/environment output — is masked out.
    ``rollout_log_probs`` must align 1:1 with ``observation_tokens`` (values outside the action
    ranges are ignored and can be left 0.0). A 1-D ``torch.Tensor``; a plain list of floats also
    works (the trainer tensor-izes it either way) but a tensor avoids that conversion.
    """

    observation_tokens: List[int]
    action_ranges: List[Tuple[int, int]]
    prompt: str
    label: Any = None
    reward: Optional[float] = None
    scores: Optional[float] = None
    rollout_log_probs: Optional[torch.Tensor] = None
    off_policy_action_lens: Optional[List[int]] = None
    truncated: bool = False
    extra_logs: dict = field(default_factory=dict)
    routed_experts: Optional[Any] = None
    group_id: Optional[str] = None
    rollout_id: Optional[str] = None


class AgentRunner(ABC):
    """A rollout driver: turns one prompt into one or more Trajectories.

    ``PRERENDER_PROMPT = False`` tells the trainer to hand the dataset's raw (unrendered) prompt
    through as-is; this runner (or whatever backs ``llm_engine``) is responsible for applying the
    model's chat template itself, exactly once, so a prompt is never double-templated.
    """

    PRERENDER_PROMPT = False

    @abstractmethod
    async def execute(
        self,
        prompt: Any,
        label: Any,
        sampling_params: Any,
        max_length: int,
        hf_tokenizer: Any,
        llm_engine: Any,
        tools: Any = None,
    ) -> Union[Trajectory, List[Trajectory]]:
        """Runs one rollout of `prompt` and returns its Trajectory (or several, for a multi-step
        agent that reports one step-sample per turn)."""


_RUNNER_CACHE: dict = {}


def load_agent_runner(agent_path: str) -> AgentRunner:
    """Imports and instantiates an AgentRunner from a "package.module:ClassName" path.

    Cached by path so repeated calls (every AgentRunnerActor construction) reuse one instance.
    """
    if agent_path not in _RUNNER_CACHE:
        module_path, _, class_name = agent_path.partition(":")
        if not class_name:
            raise ValueError(f"agent_path must be 'module.path:ClassName', got {agent_path!r}")
        runner_cls = getattr(import_module(module_path), class_name)
        _RUNNER_CACHE[agent_path] = runner_cls()
    return _RUNNER_CACHE[agent_path]
